name: GiftCode
main: GiftCode\Main
version: 1
api: [3.0.0, 4.0.0]
author: ZulfahmiFjr
translator: WolfTubeTM

commands:
 taocode:
     description: Lệnh tạo mã quà tặng
     permission: giftcode.taocode
 redeem:
     description: Lệnh đổi mã quà tặng.

permissions:
 giftcode.taocode:
     description: "Quyền để sử dụng lệnh /taocode"
     default: op